"""Update models with to_dict

Revision ID: 1c629d4d2f7f
Revises: 59ec32b35615
Create Date: 2026-03-02 10:59:37.628579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c629d4d2f7f'
down_revision = '59ec32b35615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_parcel_id'), ['parcel_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_parcel_id'), ['parcel_id'], unique=False)

    with op.batch_alter_table('parcel_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcel_statuses_parcel_id'), ['parcel_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('parcel_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcel_statuses_parcel_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_parcel_id'))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_parcel_id'))

    # ### end Alembic commands ###
